### ISSUE TITLE
python setup.py failed on Python 3.6

### ISSUE THREAD

**Issue by Joelone** [nettitude/scrounger#10]
Hi,

I'm following this instruction, and failed on the last step.
```
git pull https://github.com/nettitude/scrounger.git
cd scrounger
bash setup.sh
pip install -r requirements.txt
python setup.py develop
```
Here is the error message.
```
(py3) @joel:scrounger $ python setup.py develop
running develop
Traceback (most recent call last):
  File "setup.py", line 77, in <module>
    install_requires=['paramiko', 'biplist', 'langdetect']
  File "/opt/anaconda3/envs/py3/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/anaconda3/envs/py3/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 50, in run
    _create_custom_modules_paths()
  File "setup.py", line 17, in _create_custom_modules_paths
    for module_type in module_types.split("\n"):
TypeError: a bytes-like object is required, not 'str'

(py3) @joel:scrounger $ python -V
Python 3.6.2 :: Continuum Analytics, Inc.

```

Any clues?

Thanks,
Joel

**Comment by rdc-nettitude** [comment]
Yes, scrounger is not prepared to run with `python3`.
All tests were made using `python2.7`.
Sorry about that.

I'll have a look into it and add it as an enhancement request.

**Comment by poldenais** [comment]
HI , what's the latest iOS version and Jailbreak that Scounger modules will work with?

**Comment by zemasa** [comment]
> HI , what's the latest iOS version and Jailbreak that Scounger modules will work with?

Hi, I am personally using iOS 12.1.2 on my test device, jailbroken with unc0ver. That being said, Scrounger relies on the tools listed here: https://github.com/nettitude/scrounger/blob/master/README.md

As long as those tools work on your device, then Scrounger should not have a problem.
