### ISSUE TITLE
iOS Binaries

### ISSUE THREAD

**Issue by adaghma** [nettitude/scrounger#11]
Hi!
i get an error msg that an ios binary is not found
i moved the binaries in scrounger bin folder to /usr/bin/ on the iphone
i tried running the binary in terminal to check but i get: bad cpu type in executable

any sugs?

Thank you

**Comment by rdc-nettitude** [comment]
Looks like you're probably using an older iOS device.
The binaries were compiled for x64 devices only.
Would you be able to tell me what device you're using?

**Comment by adaghma** [comment]
is there a way i can find the source files for the binaries?

**Comment by rdc-nettitude** [comment]
Unfortunately no. I don't think we're going to support armv6/7 devices either, I'm sorry.
