### ISSUE TITLE
setup.sh

### ISSUE THREAD

**Issue by noraj** [nettitude/scrounger#14]
as `jd-cli`, `apktool` and `dex2jar` are often available in package repositories of distributions and are easy to install it is maybe proper to let user refer to https://github.com/nettitude/scrounger#required-binaries and install them himself rather than inviting him to launch `setup.sh`.

Also 

```
# install other dependencies
        apt update
        apt install libimobiledevice libusbmuxd-tools usbutils
```

won't work for any linux but just debian like.

I think the better is to remove the script and ask user to install all of that himself.

For example I already have apktools, dex2jar, jd-gui, and don't want them to be installed a second time in a local bin folder.

**Comment by rdc-nettitude** [comment]
The script is just for convenience, you don't have to use it.
I'll make sure to mention it in the README anyway. 
Cheers.

**Comment by noraj** [comment]
If I was you I would have close the issue after making the change.
