### ISSUE TITLE
Exception: 'ascii' codec can't encode character u'\u02ca' in position 952: ordinal not in range(128)

### ISSUE THREAD

**Issue by noraj** [nettitude/scrounger#21]
Hi,

Trying to parse a result i'm having an encoding error:

```
scrounger -p scrounger-report/android.analysis/results.json 

--------------------------------------------------------------------------------

[-] Exception: 'ascii' codec can't encode character u'\u02ca' in position 952: ordinal not in range(128)
```

If I open a text editor (Visual Studio Code) and make a regexp search for `[^\x00-\x7F]` (non-ascii char) I find no result.

As U+02CA seems to match with `ˊ` ([here](https://www.fileformat.info/info/unicode/char/02ca/browsertest.htm)), I added one in the doc and used the same regexp and it was detected.

So it seems there are not such non-ascii char in the report.

Plus the JSON file is a one line result so I guess that *position 952* means line 1 columns 952 but there is no weird char at this position.

I'm sorry i can't share the result file because it is confidential.

**Comment by noraj** [comment]
I made a quick ruby script to parse it myself

```ruby
require 'json'

class String
  def red;            "\e[31m#{self}\e[0m" end
  def green;          "\e[32m#{self}\e[0m" end
  def brown;          "\e[33m#{self}\e[0m" end
end

data = JSON.parse(File.open('scrounger-report/android.analysis/results.json').read)

data.each do |vuln|
  case vuln["severity"]
  when "Informational"
    print vuln["severity"]
  when "Low"
    print vuln["severity"].green
  when "Medium"
    print vuln["severity"].brown
  when "High"
    print vuln["severity"].red
  end
  puts ' ' + vuln["title"]
  #puts vuln["report"]
  vuln["details"].split('\n').each do |line|
    #puts line
  end
end
```

And the ruby standard json library doesn't seems to have a problem with it.

**Comment by zemasa** [comment]
Hi @noraj,

This one slipped through the cracks. I assume you no longer have any details on this issue?

**Comment by noraj** [comment]
Yeah the file was confidential and was destructed.
