### ISSUE TITLE
Getting an exception error when connecting an iOS device

### ISSUE THREAD

**Issue by Ally0392** [nettitude/scrounger#22]
**scrounger misc/list_apps > run 
[-] Exception**

Exception error when connecting iOS device
used iproxy for connection

iproxy 2222 22
ssh root@localhost -p 2222

no exception details is shown

**Comment by Ally0392** [comment]
Exception error when connecting iOS device
used iproxy for connection

iproxy 2222 22
ssh root@localhost -p 2222

**Comment by zemasa** [comment]
Hi @Ally0392,

Can you confirm you are able to manually SSH into the device via iproxy? (i.e., without going through Scrounger)

If you could attach some screenshots that might help. Also try setting the DEBUG and VERBOSE global variables to true, as they'll provide further information. Finally, Scrounger might've created a local file with the exception details, have a look in the filesystem.

**Comment by Ally0392** [comment]
manually SSH into the device is working
 
![image](https://user-images.githubusercontent.com/49181561/64151893-f8e16900-ce48-11e9-8ed0-da9b8d513beb.png)

only exception error occurs no details

**Comment by zemasa** [comment]
Thanks for the screenshot @Ally0392 . The DEBUG flag should output the exception, here's the relevant part of the code: https://github.com/nettitude/scrounger/blob/dd393666aa1ba1117d1c472cfdef4d0b18216904/scrounger/console/interactive.py#L163-L179

I suspect there might be something wrong with your environment. To make sure, you can try to edit those lines to remove the if statement changing the catch clause. 

Alternatively, can you try setting the output folder? Once you run the module, there should be a "scrounger.log" file within that folder, that file should also contain the exception details.

Let us know how it goes.
