### ISSUE TITLE
Android app error

### ISSUE THREAD

**Issue by Teicu** [nettitude/scrounger#23]
Hi all 

any help with this error please? Thank you

_scrounger misc/android/decompile_apk > options

Global Options:

    Name     Value
    ----     -----
    debug    False
    device
    verbose  False
    output

Module Options (misc/android/decompile_apk):

    Name    Required  Description                 Current Setting
    ----    --------  -----------                 ---------------
    output  True      local output directory      scrounger-demo-output
    apk     True      local path to the APK file  ./User/fugitif/Desktop/app-stage-release.apk_

and when I type run I get 

_scrounger misc/android/decompile_apk > run
2019-08-09 15:09:46 -                  decompile_apk : Creating decompilation directory
2019-08-09 15:09:46 -                  decompile_apk : Decompiling application
**[-] Exception: apktool binary not found.**_

**Comment by Teicu** [comment]
Note that I'm using the tool from Mac 

Cheers

**Comment by zemasa** [comment]
Hi  @Teicu,

As detailed in Scrounger's documentation, there are few binaries that are Scrounger modules' depend on: [https://github.com/nettitude/scrounger#for-android-modules](https://github.com/nettitude/scrounger#for-android-modules). Apktool is one of them.

Cheers,
