### ISSUE TITLE
Exception: apktool binary not found.

### ISSUE THREAD

**Issue by skanagaraaj** [nettitude/scrounger#24]
Hi all

any help with this error please? Thank you

_scrounger misc/android/decompile_apk > options

Global Options:

Name     Value
----     -----
debug    False
device
verbose  False
output
Module Options (misc/android/decompile_apk):

Name    Required  Description                 Current Setting
----    --------  -----------                 ---------------
output  True      local output directory      scrounger-demo-output
apk     True      local path to the APK file  ./User/fugitif/Desktop/app-stage-release.apk_
and when I type run I get

scrounger misc/android/decompile_apk > run 2019-08-09 15:09:46 - decompile_apk : Creating decompilation directory 2019-08-09 15:09:46 - decompile_apk : Decompiling application [-] Exception: apktool binary not found.

Note that I'm using the tool from Mac

**Comment by zemasa** [comment]
Hi, please refer to issue #23 : [Android app error](https://github.com/nettitude/scrounger/issues/23)
