### ISSUE TITLE
maybe pyusbmuxd is a good idea

### ISSUE THREAD

**Issue by juneJuly** [nettitude/scrounger#3]
i wrote a progam for ios app security audit , and i also used paramiko to ssh to iphone devices.

but, when i get/put some big files from/to iphone devices, that's really so so so so slow...

then i found pyusbmuxd is such a amazing solution, 

so, maybe u can take a look at pyusbmuxd, like: https://github.com/alibaba/iOSSecAudit

**Comment by rdc-nettitude** [comment]
Will definitely have a look. Cheers.

**Comment by rdc-nettitude** [comment]
Do you want to give it a go: https://github.com/nettitude/scrounger/tree/pyusbmuxd ?

**Comment by l3gi0nQQ** [comment]
@rdc-nettitude 
yep!
