### ISSUE TITLE
iOS List apps error

### ISSUE THREAD

**Issue by poldenais** [nettitude/scrounger#6]
Electra Jailbreak on iOS device (11.3.1).

I connected the device and when I try to run list_apps the following error appears below: 

```
scrounger misc/list_apps > run
2018-08-30 11:46:57 -                         device : running: which listapps
[-] Exception: listapps binary not found.
```

scrounger misc/list_apps > 2018-08-30 11:51:57 -                         device : ssh session killed

**Comment by rdc-nettitude** [comment]
That's because you've not pushed / installed the bundled binaries in the device.

Try running `misc/ios/install_binaries` first and then the `misc/list_apps` again.

Let me know if it worked fine.

**Comment by poldenais** [comment]
Thank you, this worked now as I was able to list the apps now.
